services:
  bluefeed:
    build: .
    container_name: bluefeed
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "
      echo '*/20 * * * * cd /app && /usr/local/bin/python feed.py >> /app/.cron_log 2>&1' > /etc/cron.d/bluefeed-cron &&
      chmod 0644 /etc/cron.d/bluefeed-cron &&
      crontab /etc/cron.d/bluefeed-cron &&
      touch /app/.cron_log &&
      cron && tail -f /app/.cron_log
      "